GET http://localhost:8080/statistics/task
Content-Type: application/json

###
GET http://localhost:8080/statistics/projects/times
Content-Type: application/json

###
GET http://localhost:8080/statistics/projects/task
Content-Type: application/json

###
GET http://localhost:8080/statistics/user/time
Content-Type: application/json

###
GET http://localhost:8080/statistics/days/time
Content-Type: application/json